name: Build and Deploy
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
    
      
jobs:  
  deploy:
     runs-on: ubuntu-latest  
     steps:
        - name: Checkout repository
          uses: actions/checkout@v3 # checkout the repository content to github runner
        - name: Deploy Flask app to Digital Ocean
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSHKEY }}
            port: ${{ secrets.PORT }}
            script: |
              echo "Now to the server"
              cd /home/CD/
              git pull origin master
              sudo systemctl enable --now farm
              sudo systemctl status farm
              sudo systemctl restart farm.service
              echo "Deploy completed!"             
         
           
      
    
