name: Build and Deploy
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
    
      
jobs:  
  deploy:
     runs-on: ubuntu-latest  
     steps:
        - name: Checkout repository
          uses: actions/checkout@v3 # checkout the repository content to github runner
        - name: Deploy Flask app to Digital Ocean
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSHKEY }}
            port: ${{ secrets.PORT }}
            script: |
             # Go into the right folder
             cd /home/CD/
            
             # Get the new code from Git
             git pull origin master
            
             # Restart the service
             systemctl restart farm
            
             # Check the status of the service
             systemctl status farm             
         
           
      
    
